// Generated by CoffeeScript 1.7.1
(function() {
  var MoviePanel;

  this.newApp = angular.module('newApp', []);

  MoviePanel = (function() {
    function MoviePanel($scope, $http) {
      this.$scope = $scope;
      this.$http = $http;
      $scope.search = function(amovie) {
        return $http({
          method: 'GET',
          url: 'http://www.omdbapi.com/',
          params: {
            s: amovie
          }
        }).success(function(data, status, headers, config) {
          return $scope.movieList = data.Search;
        }).error(function(data, status, headers, config) {});
      };
      $scope.showDetails = function(movie) {
        return $http({
          method: 'GET',
          url: 'http://www.omdbapi.com/',
          params: {
            i: movie.imdbID
          }
        }).success(function(data, status, headers, config) {
          $scope.moviePlot = data.Plot;
          $scope.moviePoster = data.Poster;
          return $scope.movieTitle = data.Title;
        }).error(function(data, status, headers, config) {});
      };
    }

    return MoviePanel;

  })();

  MoviePanel.$inject = ["$scope", "$http"];

  newApp.controller("MoviePanel", MoviePanel);

}).call(this);
